import type { Metadata } from "next";
import { Instrument_Sans } from "next/font/google";
import "./globals.scss";
import Provider from "@/components/Provider";

const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Recruito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${instrumentSans.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Provider children={children} />
      </body>
    </html>
  );
}
