import type { Metadata } from "next";

/* Start of the instrument\_sans font */
import { Instrument_Sans } from "next/font/google";
const instrumentSans = Instrument_Sans({
  variable: "--font-instrument-sans",
  subsets: ["latin"],
});
/* end of the instrument\_sans font */

/* Main css file */
import "./globals.scss";
/* WEnd iof the main css file */

/* Fontawesome */
import "@/lib/fontawesome";
/* End of the fontawesome */

/* Swiper */
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Footer from "@/components/Footer";
/* End of the swiper */

export const metadata: Metadata = {
  title: "Recruito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${instrumentSans.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}

        <Footer />

        <div id="portal-root" />
      </body>
    </html>
  );
}
